var tamilnadu = ["Ariyalur","Chengalpattu","Chennai","Coimbatore","Cuddalore","Dharmapuri","Dindigul","Erode","Kallakurichi","Kanchipuram","Kanyakumari","Karur","Krishnagiri","Madurai","Nagapattinam","Namakkal","Nilgiris","Perambalur","Pudukkottai","Ramanathapuram","Ranipet","Salem","Sivaganga","Tenkasi","Thanjavur","Theni","Thoothukudi (Tuticorin)","Tiruchirappalli","Tirunelveli","Tirupathur","Tiruppur","Tiruvallur","Tiruvannamalai","Tiruvarur","Vellore","Viluppuram","Virudhunagar"];
var andrapradesh = ['Anantapur','Chittoor','East Godavari','Guntur','YSR Kadapa','Krishna','Kurnool','Prakasam','Sri Potti Sriramulu Nellore','Srikakulam','Visakhapatnam','Vizianagaram','West Godavari'];

var district = [
    ['Andhra Pradesh','Anantapur'],
    ['Andhra Pradesh','Chittoor'],
    ['Andhra Pradesh','East Godavari'],
    ['Andhra Pradesh','Guntur'],
    ['Andhra Pradesh','YSR Kadapa'],
    ['Andhra Pradesh','Krishna'],
    ['Andhra Pradesh','Kurnool'],
    ['Andhra Pradesh','Prakasam'],
    ['Andhra Pradesh','Sri Potti Sriramulu Nellore'],
    ['Andhra Pradesh','Srikakulam'],
    ['Andhra Pradesh','Visakhapatnam'],
    ['Andhra Pradesh','Vizianagaram'],
    ['Andhra Pradesh','West Godavari'],
    ['Tamil Nadu','Ariyalur'],
    ['Tamil Nadu','Chengalpattu'],
    ['Tamil Nadu','Chennai'],
    ['Tamil Nadu','Coimbatore'],
    ['Tamil Nadu','Cuddalore'],
    ['Tamil Nadu','Dharmapuri'],
    ['Tamil Nadu','Dindigul'],
    ['Tamil Nadu','Erode'],
    ['Tamil Nadu','Kallakurichi'],
    ['Tamil Nadu','Kanchipuram'],
    ['Tamil Nadu','Kanyakumari'],
    ['Tamil Nadu','Karur'],
    ['Tamil Nadu','Krishnagiri'],
    ['Tamil Nadu','Madurai'],
    ['Tamil Nadu','Nagapattinam'],
    ['Tamil Nadu','Namakkal'],
    ['Tamil Nadu','Nilgiris'],
    ['Tamil Nadu','Perambalur'],
    ['Tamil Nadu','Pudukkottai'],
    ['Tamil Nadu','Ramanathapuram'],
    ['Tamil Nadu','Ranipet'],
    ['Tamil Nadu','Salem'],
    ['Tamil Nadu','Sivaganga'],
    ['Tamil Nadu','Tenkasi'],
    ['Tamil Nadu','Thanjavur'],
    ['Tamil Nadu','Theni'],
    ['Tamil Nadu','Thoothukudi (Tuticorin)'],
    ['Tamil Nadu','Tiruchirappalli'],
    ['Tamil Nadu','Tirunelveli'],
    ['Tamil Nadu','Tirupathur'],
    ['Tamil Nadu','Tiruppur'],
    ['Tamil Nadu','Tiruvallur'],
    ['Tamil Nadu','Tiruvannamalai'],
    ['Tamil Nadu','Tiruvarur'],
    ['Tamil Nadu','Vellore'],
    ['Tamil Nadu','Viluppuram'],
    ['Tamil Nadu','Virudhunagar']
]